apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches: 
  - patch: |-
      - op: replace
        path: /spec/policies/0
        value: dev-policy-allowed-repos
    target:
      kind: PolicySet
  - patch: |-
      - op: replace
        path: /subjects/0/name
        value: dev-policies-gatekeeper
      - op: replace
        path: /placementRef/name
        value: dev-placement-policies-gatekeeper
    target:
      kind: PlacementBinding

namespace: dev-gatekeeper
namePrefix: dev-

resources: 
  - ../../constraints

patchesStrategicMerge:
  - placementrule.yaml