apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches: 
  - patch: |-
      - op: replace
        path: /apiVersion
        value: templates.gatekeeper.sh/v1alpha1
    target:
      kind: ConstraintTemplate

resources:
  - https://github.com/momoah/gatekeeper-library/tree/master/library/general
# You can optionally install a subset by specifying a subfolder, or specify a commit SHA
# - github.com/open-policy-agent/gatekeeper-library/library/pod-security-policy?ref=0c82f402fb3594097a90d15215ae223267f5b955
