apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true, Prune=false
  name: placement-policies-gatekeeper
  namespace: acm-gatekeeper
spec:
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - prod